/**  */
import jsdom from 'jsdom';

import {
  fetchText,
  getChildren,
  getLeaf,
  getMdast,
  getTable,
  getTableMap,
  getKeyVals,
  nodeContains,
  saveDocx,
  updateKeyName,
  updateKeyNameAndValue,
  updateKeyValue,
} from './utils/mdast-utils.js';

// list of urls of Franklin pages to update
const pages = [
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/aaa-northeast-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/aaa-northeast-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/abb-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/academy-of-art-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/accent-group-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/accor-hotels-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/aci-worldwide-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/adobe-advertising-cloud-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/adobe-at-adobe-techsummit-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/adobe-campaign-orchestration-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/adobe-connect-elearning-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/adobe-content-hub-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/adobe-digital-experiences-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/adobe-digital-onboarding-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/adobe-digital-university-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/adobe-embed-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/adobe-experience-cloud-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/adobe-experience-platform-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/adobe-inside-adobe-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/adobe-legal-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/adobe-on-adobe-customer-activity-hub-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/adobe-on-adobe-intranet-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/adobe-on-adobe-io-runtime-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/adobe-platinum-partners-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/adobe-sensei-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/adobe-xml-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/adp-workfront-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/airbus-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/aisg-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/al-ghandi-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/algonquin-college-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/allianz-australia-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/alma-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/alpen-group-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/alshaya-group-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/altisource-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/americord-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/amplifon-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/aon-hewitt-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/armor-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/asics-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/asus-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/at-home-japan-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/autoanything-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/avidxchange-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/avionte-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/bancsource-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/bank-of-new-zealand-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/barilla-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/bask-digital-media-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/bauhaus-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/bbva-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/bbva-workfront-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/beer-hawk-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/ben-and-jerrys-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/benefytt-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/bettercloud-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/big-bus-tours-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/binyan-studios-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/blackmores-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/bmf-aldi-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/bmw-group-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/bmw-group-france-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/border-states-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/bose-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/boston-university-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/brafton-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/brand-safety-institute-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/breadcrumbs',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/bridgestone-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/briggs-stratton-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/bsi-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/bt-sign-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/bt-sport-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/bulk-powders-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/bupa-uk-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/burberry-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/ca-assembly-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/cal-state-fullerton-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/cambridge-assessment-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/camelot-3pl-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/carmax-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/carnegie-hall-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/casio-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/catbird-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/cats-protection-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/cbre-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/cdw-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/center-parcs-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/century-link-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/change-healthcare-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/charles-schwab-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/charles-sturt-university-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/chemours-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/chg-workfront-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/chhaya-prakashani-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/chipotle-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/cibc-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/ciena-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/cisco-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/city-county-denver-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/city-of-sacramento-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/coca-cola-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/code-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/cognizant-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/cohelion-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/columbia-shipmanagement-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/commvault-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/compensar-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/comviva-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/constellation-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/courts-asia-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/creative-reaction-lab-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/cupid-media-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/cushman-wakefield-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/cxc-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/cylance-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/davis-school-district-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/dccu-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/dche-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/deakin-university-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/dell-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/delta-and-kin-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/dentsu-isobar-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/destination-imagination-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/devro-workfront-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/digima-asia-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/dixons-carphone-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/dominos-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/dun-and-bradstreet-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/edf-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/edmunds-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/egencia-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/electronics-for-imaging-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/elektrobit-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/empowered-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/epson-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/esri-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/esri-workfront-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/etsu-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/evisort-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/f5-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/facebook-gaming-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/fcb-workfront-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/firstservices-residential-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/fis-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/flight-centre-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/foodpanda-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/foodservicedirect-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/forever-new-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/fox-networks-group-gmbh-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/freshform-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/fsr-connect-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/ftd-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/full-sail-university1-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/full-sail-university-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/galenica-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/galliford-try-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/gallo-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/gebruder-weiss-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/ge-healthcare-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/georgia-pacific-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/global-fund-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/global-reach-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/godirect-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/golden-state-warriors-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/green-mountain-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/green-rock-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/grundfos-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/gs-retail-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/guerrilla-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/hagerty-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/hakuhodo-i-studio-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/hallmark-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/havas-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/hbr-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/healthgrades-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/helly-hansen-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/hesta-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/hewlett-packard-enterprise-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/hipages-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/hitachi-solutions-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/homag-group-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/hostelworld-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/hotelscom-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/hp-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/hugo-boss-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/hugo-marie-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/huk-coburg-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/hyatt-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/hyundai-mnsoft-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/ibm-2022-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/ibm-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/iehp-workfront-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/ies-communications-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/ihmvcu-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/imm-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/industry-west-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/informatica-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/innogy-se-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/iowa-state-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/itv-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/jaguar-land-rover-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/james-hardie-building-products-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/japan-airlines-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/japantaxi-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/jcb-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/jiva-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/jll-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/jobcenter-kolding-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/jockey-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/jomashop-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/juniper-networks-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/kao-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/karcher-studio-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/kddi-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/kennards-hire-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/keybank-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/killer-ink-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/kindred-healthcare-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/king-com-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/kiwibank-workfront-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/k-line-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/kolbe-academy-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/komax-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/kws-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/ladpss-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/lafayette-148-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/la-rams-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/lash-group-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/layerx-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/learning-guild-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/legalvision-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/lenovo-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/liberty-mutual-insurance-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/liebherr-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/life-fitness-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/life-sciences-company-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/lifesize-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/limbitless-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/loccitane-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/london-heathrow-airport-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/lookers-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/lovesac-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/lush-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/mainline-menswear-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/manulife-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/marc-fisher-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/marie-claire-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/market-america-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/marks-spencer-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/marriott-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/master-electronics-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/mattel-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/maxim-integrated-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/mcgrath-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/merck-kgaa-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/merck-workfront-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/mercy-health-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/metro-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/meyer-natural-foods-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/milwaukee-bucks-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/ministero-del-turismo-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/mitel-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/mobiles-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/mondi-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/morningstar-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/mouser-workfront-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/msi-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/national-bank-of-canada-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/national-center-for-missing-and-exploited-children-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/natwest-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/nedbank-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/neo4j-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/neverfail-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/nintex-k2-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/nissan-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/nissin-foods-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/nordstrom-fusion-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/norfolk-county-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/novozymes-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/npfmc-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/nrg-energy-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/nten-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/obramax-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/ocbc-bank-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/occu-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/ogilvy-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/oppenheimer-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/orvis-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/otto-collaboration-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/otto-e-commerce-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/oxygen-media-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/palo-alto-networks-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/panasonic-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/paper-moose-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/paul-smith-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/pelco-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/penn-state-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/penn-state-workfront-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/perficient-digital-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/performance-health-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/persol-holdings-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/pes-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/pga-tour-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/philips-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/piaggio-fast-forward-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/pitchbook-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/pitney-bowes-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/placer-county-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/planet-forward-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/platform-housing-group-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/police-ict-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/portland-trail-blazers-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/prakria-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/princess-cruises-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/prismhr-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/progrexion-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/publicis-media-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/puma-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/qatar-tourism-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/qpac-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/quick-corp-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/rcs-mediagroup-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/redstone-federal-credit-union-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/redtag-ca-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/regeneron-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/relativity-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/retail-apparel-group-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/ringcentral-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/ripple-effect-images-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/rising-sun-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/rite-aid-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/roche-diagnostics-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/roche-diagnostics-marketo-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/rochester-institute-of-technology-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/rossignol-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/rs-components-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/rubicon-heritage-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/rubiks-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/rural-king-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/ryder-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/sage-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/saint-gobain-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/sally-beauty-holdings-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/salon-centric-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/san-francisco-tax-office-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/sas-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/save-the-children-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/schneider-electric-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/scuf-gaming-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/sealed-air-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/seismic-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/selco-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/seniority-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/shinola-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/shoebacca-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/showtime-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/silicon-labs-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/sinking-ship-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/sixt-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/skipton-building-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/skylark-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/sky-uk-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/slater-gordon-group-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/sleepx-goji-web-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/smbxl-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/soak-and-sleep-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/social-kinnect-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/software-ag-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/sony-bank-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/sony-interactive-entertainment-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/sprint1-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/sprint-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/stanley-black-decker-workfront-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/starhub-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/state-of-vermont-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/stoke-group-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/strabag-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/strauss-coffee-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/stv-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/sugarfina-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/swisscom-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/synopsys-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/tasktop-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/tata-consulting-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/tavant-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/teg-analytics-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/telefonica-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/telegraph-media-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/telenor-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/televerde-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/tess-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/the-home-depot-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/thermo-fisher-scientific-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/the-simply-group-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/thomas-college-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/thomas-jefferson-university-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/tintri-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/tip-trailer-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/tivo-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/tmobile-workfront-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/tom-dixon-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/training-magazine-network-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/trane-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/transcat-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/transparent-bpo-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/travelocity-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/trimble-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/tsb-bank-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/tsb-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/uc-davis-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/uci-ocean-agency-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/uhcu-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/unc-chapel-hill-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/under-armour-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/university-of-utah-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/us-census-bureau-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/usmc-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/varian-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/viacomcbs-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/vice-media-post-production-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/viega-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/vink-vts-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/virgin-atlantic-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/virgin-holidays-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/visier-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/vistaprint-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/vistaprint-india-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/vodafone-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/vodafone-training-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/vw-classic-parts-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/walgreens-boots-alliance-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/watsco-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/waymark-tech-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/weber-state-university-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/western-digital-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/westjet-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/wild-advertising-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/wssu-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/wwf-australia-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/wyze-labs-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/xfinity-creative-customer-story',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/xpjp-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/yakima-chief-hops-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/yayoi-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/ypo-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/zdf-enterprises-case-study',
  'https://main--bacom--adobecom.hlx.page/customer-success-stories/zebra-technologies-case-study',
];

const arrow = ' ›';

const properLinks = {
  Acrobat: [
    'https://www.adobe.com/acrobat.html',
    'https://acrobat.adobe.com/us/en/acrobat/acrobat-pro.html',
    'https://acrobat.adobe.com/us/en/acrobat.html',
    'https://www.adobe.com/products/acrobat.html',
    'https://www.adobe.com/acrobat/business.html',
  ],
  'Acrobat DC': [
    'https://acrobat.adobe.com/us/en/acrobat/business.html',
    'https://www.adobe.com/acrobat.html',
  ],
  'Acrobat Sign Embed Program':
    'https://acrobat.adobe.com/us/en/documentcloud/integrations/isv-partner-program.html',
  'Acrobat Sign': [
    'https://www.adobe.io/apis/documentcloud/sign.html',
    'https://acrobat.adobe.com/us/en/industries/education.html',
    'https://www.adobe.com/sign.html',
    'https://acrobat.adobe.com/us/en/sign.html',
    'https://acrobat.adobe.com/us/en/sign/business.html',
  ],
  'Advertising Cloud': [
    'https://www.adobe.com/creativecloud/business/enterprise.html',
    'https://business.adobe.com/products/advertising/adobe-advertising-cloud.html',
    'https://business.adobe.com/products/advertising/adobe-advertising-cloud',
    'https://business.adobe.com/index/topics/advertising.html',
  ],
  Analytics: [
    'https://business.adobe.com/products/analytics/adobe-analytics.html',
    'https://business.adobe.com/products/analytics/web-analytics.html',
    'https://business.adobe.com/products/analytics/adobe-analytics',
    'https://business.adobe.com/index/topics/analytics.html',
  ],
  'Audience Manager': [
    'https://business.adobe.com/products/audience-manager/adobe-audience-manager.html',
    'https://business.adobe.com/products/audience-manager/adobe-audience-manager',
    'https://business.adobe.com/products/audience-manager.html',
  ],
  Campaign: 'https://business.adobe.com/products/campaign/adobe-campaign.html',
  Captivate: 'https://www.adobe.com/products/captivate.html',
  Commerce: [
    'https://business.adobe.com/products/magento/magento-commerce.html',
    'https://business.adobe.com/solutions/commerce.html',
  ],
  'Consulting Services': [
    'https://business.adobe.com/customers/consulting-services/main.html',
    'https://www.adobe.com/experience-cloud/consulting-services.html',
  ],
  'Creative Cloud': [
    'https://www.adobe.com/creativecloud.html',
    'https://www.adobe.com/creativecloud/business/enterprise.html',
    'https://www.adobe.com/creativecloud/plans.html',
    'https://www.adobe.com/creativecloud/buy/education.html',
  ],
  'Creative Cloud for education': 'https://www.adobe.com/education.html',
  'Creative Cloud for enterprise': ['https://www.adobe.com/creativecloud/business/enterprise.html'],
  'Creative Cloud for teams': 'https://www.adobe.com/creativecloud/business/teams.html',
  'Customer Journey Analytics':
    'https://business.adobe.com/products/experience-platform/customer-journey-analytics.html',
  'Customer Solutions': [
    'https://business.adobe.com/customers/consulting-services/main.html',
    'https://business.adobe.com/support/main.html',
  ],
  'Document Cloud': [
    'https://acrobat.adobe.com/us/en/business.html',
    'https://acrobat.adobe.com/us/en/',
    'https://www.adobe.com/documentcloud.html',
    'https://business.adobe.com/',
    'https://www.adobe.com/business.html',
  ],
  'Experience League': [
    'https://experienceleague.adobe.com/#dashboard/welcome',
    'https://experienceleague.adobe.com/',
  ],
  'Experience Manager': [
    'https://business.adobe.com/products/experience-manager/sites/aem-sites.html',
    'https://business.adobe.com/products/experience-manager/adobe-experience-manager.html',
    'https://business.adobe.com/products/experience-manager/adobe-experience-manager',
    'https://business.adobe.com/index/topics/content-management.html',
  ],
  'Experience Manager Assets as a Cloud Service':
    'https://business.adobe.com/products/experience-manager/assets/aem-assets.html',
  'Experience Manager Sites as a Cloud Service':
    'https://business.adobe.com/products/experience-manager/sites/aem-sites.html',
  Express: 'https://www.adobe.com/express/',
  Illustrator: 'https://www.adobe.com/products/illustrator.html',
  InDesign: 'https://www.adobe.com/products/indesign.html',
  'Learning Manager':
    'https://business.adobe.com/products/learning-manager/adobe-learning-manager.html',
  'Marketo Engage': [
    'https://business.adobe.com/products/marketo/adobe-marketo.html',
    'https://www.marketo.com/',
    'https://www.marketo.com/marketo-engage/',
    'https://www.adobe.com/marketing/marketo.html',
  ],
  'Marketo Measure': 'https://www.marketo.com/bizible/',
  Photoshop: [
    'https://www.adobe.com/products/photoshop.html',
    'https://www.adobe.com/products/photoshop/landpa.html',
  ],
  'Premiere Pro': 'https://www.adobe.com/products/premiere.html',
  'Premiere Rush': 'https://www.adobe.com/products/premiere-rush.html',
  'Professional Services': [
    'https://landing.adobe.com/acs/why-APS.html',
    'https://business.adobe.com/customers/consulting-services/main.html',
  ],
  Sensei: 'https://www.adobe.com/sensei.html',
  Sign: [
    'https://acrobat.adobe.com/us/en/sign/business.html',
    'https://www.adobe.com/sign.html',
    'https://acrobat.adobe.com/us/en/sign.html',
    'https://www.adobe.com/sign/business.html',
  ],
  Spark: 'https://www.adobe.com/products/spark.html',
  Stock: ['https://stock.adobe.com/', 'https://www.adobe.com/creativecloud/stock.html'],
  'Substance 3D Collection': 'https://www.adobe.com/products/substance3d/business.html',
  'Substance 3D Stager': 'https://www.adobe.com/products/substance3d-stager.html',
  Target: [
    'https://business.adobe.com/products/target/adobe-target.html',
    'https://business.adobe.com/index/topics/personalization.html',
    'https://business.adobe.com/products/target.html',
  ],
  Workfront: [
    'https://business.adobe.com/products/workfront/main.html',
    'https://www.workfront.com/',
    'https://www.workfront.com/ppc/enterprise-project-management',
  ],
  XD: 'https://www.adobe.com/products/xd.html',
  'Frame.io': [
    'https://frame.io/',
    'https://www.adobe.com/creativecloud/business/enterprise/frameio.html',
    'https://www.adobe.com/creativecloud/video/review-and-collaboration.html',
  ],
};

const urlError = (page, text, expected, actual) =>
  console.log(`
${page
  .replace('https://main--bacom--adobecom.hlx.page/customer-success-stories/', '')
  .replace('', '')} : ${text}
    Url Mismatch
    Exp: ${expected}
    Got: ${actual}`);

const checkLink = (page, txt, link) => {
  const text = txt.startsWith('Adobe ') ? txt.substring(6) : txt;
  if (!text || !link || !properLinks[text]) return;

  if (Array.isArray(properLinks[text])) {
    if (!properLinks[text].includes(link)) {
      urlError(page, text, properLinks[text], link);
    }
  } else if (link !== properLinks[text]) {
    urlError(page, text, properLinks[text], link);
  }
};

const main = async () => {
  console.log('300-500');
  // for (const page of pages.slice(300, 500)) {
  for (const page of pages) {
    let html = await fetchText(`${page}.md`);
    if (!html) {
      console.log('Error: ', page);
      continue;
    }
    if (html.includes('**media')) {
      const i = html.indexOf('** media');
      console.log('media: ', html.slice(i, i + 10), page);
    }
    /*

    // const parser = new DOMParser();
    // const doc = parser.parseFromString(html, 'text/html');
    const dom = new jsdom.JSDOM(html);
    const statsBlock = dom.window.document.querySelector('.stats');
    if (!statsBlock) {
      console.log('No stats block found:', page);
      continue;
    }

    statsBlock.querySelectorAll('a').forEach((a) => {
      const text = a.textContent?.replace(arrow, '');
      checkLink(page, text, a.href);
    });
    */
  }
};

await main();
process.exit(0);
