import fs from 'fs';
import { fetch } from '@adobe/fetch';
import { loadDocument } from './document-manager/document-manager.js';

/**
 * Loads a list of entries from a Query Index.
 *
 * @param {*} url - The URL to fetch the data from.
 * @returns {Promise<string[]>} - List of entries.
 */
export async function loadQueryIndex(url, fetchFunction = fetch) {
  const entries = [];
  const response = await fetchFunction(url);

  if (!response.ok) {
    throw new Error(`Failed to fetch data from ${url}`);
  }

  const json = await response.json();
  const { total, offset, limit, data } = json;

  entries.push(...data.map((entry) => entry.path));
  const remaining = total - offset - limit;
  if (remaining > 0) {
    const nextUrl = `${url}?limit=${limit}&offset=${offset + limit}`;
    entries.push(...await loadQueryIndex(nextUrl, fetchFunction));
  }

  return entries;
}

/**
 * Loads entries from a source. The source can be an array, a comma-separated string,
 * a string starting with '/', a URL pointing to a JSON file, a local path to a JSON file,
 * or a local path to a TXT file.
 *
 * @param {string|string[]} source - The list of entries to load from.
 * @returns {Promise<string[]>} - The loaded data as an array of strings.
 * @throws {Error} - If the list format or entry is unsupported.
 */
export async function loadListData(source, fetchFunction = fetch) {
  if (Array.isArray(source) || source.includes(',')) {
    const entries = Array.isArray(source) ? source : source.split(',');
    return (await Promise.all(entries.map((entry) => loadListData(entry.trim())))).flat();
  }
  const extension = source.includes('.') ? source.split('.').pop() : null;

  if (!extension) {
    return [source];
  }

  switch (extension) {
    case 'json':
      if (source.startsWith('http')) {
        return loadQueryIndex(source, fetchFunction);
      }
      return JSON.parse(fs.readFileSync(source, 'utf8').trim());
    case 'txt':
      return fs.readFileSync(source, 'utf8').trim().split('\n');
    default:
      throw new Error(`Unsupported list format or entry: ${source}`);
  }
}

/**
 * Executes a bulk update operation using the provided migration function
 * Loads data from various sources and executes bulk update operations from the migration function.
 *
 * @param {object} config - The configuration object.
 * @param {function} migrate - The migration function.
 * @param {object} [reporter=null] - Override reporter object.
 * @returns {object} - The totals generated by the reporter.
 */
export default async function main(config, migrate, reporter = null) {
  config.reporter ??= reporter;

  try {
    const entryList = await loadListData(config.list);

    for (const [i, entry] of entryList.entries()) {
      console.log(`Processing entry ${i + 1} of ${entryList.length} ${entry}`);
      const document = await loadDocument(entry, config);
      await migrate(document);
    }
  } catch (e) {
    console.error('Bulk Update Error:', e);
  }

  return config.reporter.generateTotals();
}

/**
 * Executes a bulk update operation using a migration script, loading data from various sources
 * and executing bulk update operations from the migration script.
 *
 * npm run bulk-update <project> <list>
 */
if (import.meta.url === `file://${process.argv[1]}`) {
  const args = process.argv.slice(2);
  const [migrationFolder, list = null] = args;
  const migrationFile = `${process.cwd()}/${migrationFolder}/migration.js`;
  // eslint-disable-next-line import/no-dynamic-require, global-require
  const migration = await import(migrationFile);
  const config = migration.init();
  config.list = list || config.list;

  await main(config, migration.migrate);
  process.exit(0);
}
